# Simple workflow for deploying static content to GitHub Pages
name: Reproduce results

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:


jobs:
  run:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/scientificcomputing/fenics-gmsh:2023-08-16

    steps:
      - uses: actions/checkout@v4

      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/instant
            ~/.cache/dijitso
          key: cache_v1
          restore-keys: |
            cache_v1

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Run simple sphere
        run: python3 sphere_simple.py

      - name: Run anisotropic sphere
        run: python3 sphere_simple.py

      - name: Run ellipsoid
        run: python3 ellipsoid.py

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: |
            ./spheres
            ./ellipsoids
            ./results_ellipsoid
            ./results_sphere_simple
            ./results_sphere_anisotropic
          if-no-files-found: error
